import google.generativeai as genai
from app.core.config import get_settings
import json
import re
import logging
import asyncio

settings = get_settings()

genai.configure(api_key=settings.GEMINI_API_KEY)

GEMINI_MODEL = "gemini-2.5-flash"

async def generate_content(prompt: str, model: str = None) -> str:
    target_model = model or GEMINI_MODEL
    gemini = genai.GenerativeModel(target_model)
    # google-generativeai's generate_content is synchronous,
    # so run it in a thread executor to avoid blocking the event loop
    loop = asyncio.get_event_loop()
    response = await loop.run_in_executor(None, gemini.generate_content, prompt)
    return response.text


async def extract_topics(text: str) -> list:
    prompt = f"""
    Analyze the following text and extract key topics. 
    Return a JSON list of strings.
    Text: {text[:10000]}... (truncated)
    """
    response = await generate_content(prompt)
    result = _parse_json(response)
    return result if isinstance(result, list) else []

async def generate_explanations(text: str, topics: list) -> dict:
    prompt = f"""
    For each of the following topics, provide a detailed explanation based on the text.
    Topics: {topics}
    Text: {text[:10000]}...
    Return a JSON object where keys are topics and values are explanations.
    """
    response = await generate_content(prompt)
    result = _parse_json(response)
    return result if isinstance(result, dict) else {}

async def generate_mind_tree(text: str) -> dict:
    prompt = f"""
    Create a hierarchical mind map of the concepts in the text.
    Return a JSON structure representing the tree. 
    IMPORTANT RULES:
    1. Do NOT use indexes or numbering (like "1.", "1.1") in the topic names.
    2. Only include the most important, highly relevant topics to related to their parent.
    3. REMOVE unnecessary contents like introductions, summaries, or basic definitions. Focus on core concepts.
    4. Keep node names concise.
    5. EXACT FORMAT: You must return a single JSON object with EXACTLY two keys: "name" (a string for the concept) and "children" (an array of objects with the exact same structure). Do NOT use any other format!
       Example: {{"name": "Root Concept", "children": [{{"name": "Sub Concept", "children": []}}]}}
    Text: {text[:10000]}...
    """
    response = await generate_content(prompt)
    result = _parse_json(response)
    # the frontend normalization will also handle any structure differences just in case
    return result if isinstance(result, dict) or isinstance(result, list) else {}

async def generate_predicted_questions(text: str) -> list:
    prompt = f"""
    Predict 5 potential exam questions based on the text.
    Return a JSON list of objects with 'question' and 'answer' keys.
    Text: {text[:10000]}...
    """
    response = await generate_content(prompt)
    result = _parse_json(response)
    return result if isinstance(result, list) else []


def _parse_json(text: str):
    # Remove thinking blocks generated by reasoning models
    text = re.sub(r'<think>.*?</think>', '', text, flags=re.DOTALL)
    
    # Helper to extract JSON from LLM response
    text = text.strip()
    
    # Try to find ```json ... ``` block
    match = re.search(r"```(?:json)?\s*(.*?)\s*```", text, re.DOTALL)
    if match:
        text = match.group(1)
    else:
        # Fallback: try to find the first [ or { and the last ] or }
        idx_brace = text.find('{')
        idx_bracket = text.find('[')
        # Filter out -1s
        valid_starts = [i for i in (idx_brace, idx_bracket) if i != -1]
        
        if valid_starts:
            first_bracket = min(valid_starts)
            last_brace = text.rfind('}')
            last_bracket = text.rfind(']')
            last_char = max(last_brace, last_bracket)
            if last_char != -1 and last_char >= first_bracket:
                text = text[first_bracket:last_char+1]
                
    try:
        return json.loads(text)
    except json.JSONDecodeError as e:
        print(f"Failed to parse JSON: {e}\nRaw text was:\n{text}")
        return {}
